### ISSUE TITLE
Navigating tabs with Redux

### ISSUE THREAD

**Issue by ctsrc** [bencompton/framework7-redux#11]
Hi, I am using tabs in my Framework7 + React + Redux app and am wondering how to integrate tabs with Redux properly. Currently I am still using href links as I originally did when using Framework7 + React without Redux, but as per the framework7-redux README, this is not what I should be doing. For other links and buttons I am using onClick to call actions, but I don't know how to make actions that will work with tabs.

I have created a minimal sample app to demonstrate what it looks like: https://github.com/ctsrc/framework7-redux-app-template/tree/c28a98ea64514db44fab70a9dd9063941ee6830b

Here is a static build of it, so that one can have a look at it without having to clone and run it locally: https://ctsrc.github.io/framework7-redux-app-template/c28a98ea64514db44fab70a9dd9063941ee6830b/

In particular, make note of what happens when using the links in each of the two first tabs to navigate to other pages. On the home page (first tab), both links that use the framework7-redux navigateTo work as intended, whereas on tab two only the popup link works as it should.

What happens on the second tab is that Redux performs the navigation in the first tab, which makes sense of course since Redux is unaware of the tabs. Question is, how do I properly integrate the tabs with Redux?

**Comment by ctsrc** [comment]
Here is a static build of it, so that one can have a look at it without having to clone and run it locally: https://ctsrc.github.io/framework7-redux-app-template/b73dc40808a8425acf2eca633c610dd1aa4fe599/

**Comment by ctsrc** [comment]
And to reiterate since I wrote quite a bit of text: My question is how to properly integrate routable tabs with Redux.

**Comment by ctsrc** [comment]
By the way, if you are reading this issue and the comments on it through your e-mail client then please note that I've made several edits since I first submitted it, meaning that the copies of the text that GitHub sent you by e-mail are now out of date. Please ignore the out of date version that GitHub sent you by e-mail and use the GitHub website to read it instead. https://github.com/bencompton/framework7-redux/issues/11

**Comment by bencompton** [comment]
@ctsrc - looking at your [routes.js](https://github.com/ctsrc/framework7-redux-app-template/blob/c28a98ea64514db44fab70a9dd9063941ee6830b/src/routes.js) file, I don't see any [tab routes](http://framework7.io/docs/tabs.html#routable-tabs) defined. You will first need to update your routes.js to link your tabs to routes and define what components show in your tabs when they're selected.

**Comment by ctsrc** [comment]
I've updated it to use routable tabs, but I am not getting it to work as it should.

Static build: https://ctsrc.github.io/framework7-redux-app-template/4b842ea4b4357405f223b89f95d0ef789ff6b813/

Source: https://github.com/ctsrc/framework7-redux-app-template/tree/4b842ea4b4357405f223b89f95d0ef789ff6b813

After you've loaded the page you can go to either tab 2 or tab 3, but after navigating to either of those tabs, no further tab navigation is possible. The catalog and item links are also broken in various confusing ways.

**Comment by bencompton** [comment]
I see that the components you're using in your tab routes are pages. What goes inside of a tab shouldn't be a page. The goal of tab routes is to have the main route be a page containing the tabs, with tab routes underneath of it containing the components that go inside of the tabs.

**Comment by ctsrc** [comment]
I've changed it now so that it doesn't use pages in tabs

Staic build: https://ctsrc.github.io/framework7-redux-app-template/fdf7ee8440490d46182d2a114ac61d89b6ac343c/

Source: https://github.com/ctsrc/framework7-redux-app-template/tree/fdf7ee8440490d46182d2a114ac61d89b6ac343c

but the problem remains the same:

> After you've loaded the page you can go to either tab 2 or tab 3, but after navigating to either of those tabs, no further tab navigation is possible. The catalog and item links are also broken in various confusing ways.

**Comment by ctsrc** [comment]
Do you have any suggestions?

**Comment by bencompton** [comment]
@ctsrc, I can get it to work by changing the calls to navigate to to replace the current history entry: `navigateTo('/tab-route/tab1/', true)`. Otherwise, it appears to be causing problems with reconciliation in F7 Redux. That shouldn't be much of a problem, because unlike navigating between pages where you can go back, going back isn't very useful with tabs.

EDIT:

To add more detail in case you're curious, it appears that F7 itself doesn't keep track of the history of tabs, whereas F7 Redux does. F7 Redux has a reconciliation algorithm where it compares the history in the store to F7's history, and then determines the steps required to make them match (i.e., make F7 navigate forward or back). The fact that F7 isn't updating the history for tab changes causes problems when F7 Redux does have history for the tabs.

Anyhow, I always use `navigateTo('/some-page/tab1/', true)` in my own apps, and have never had a reason to do otherwise. It's technically a bug, I suppose, but probably not a huge priority in my mind.

**Comment by ctsrc** [comment]
Telling navigateTo to replace the current history entry makes the tab navigation work.

And the "item 23" pop-up links still work.

Unfortunately however, the "catalog" links in each of the first two tabs still don't work, and if you click one of the "catalog" links before you click one of the pop-up links it still messes up what happens when you click the "item 23" pop-up link afterwards.

Static build: https://ctsrc.github.io/framework7-redux-app-template/04e1256ceec0cda0883a8e5ccd4aa119ea006a89/

Source: https://github.com/ctsrc/framework7-redux-app-template/tree/04e1256ceec0cda0883a8e5ccd4aa119ea006a89

Thank you for your help so far.

I hope you have time to help me resolve this completely.

**Comment by bencompton** [comment]
The issue is you're not just navigating between tabs, you're also navigating from "page" to "page" within tabs. In order to really do that properly, the structure of the history gets more complicated, because now each tab has to have its own history to allow switching between tabs and to have each tab keep its current page when switching back. Framework7 does support putting each tab into a separate view, and then each view can have its own history that is separate from the main history in the main view, but Framework7 Redux only currently supports using actions to navigate the main view. The problem also with putting each tab in a separate view is that your app can only have one set of tabs. So, say your app has a home page that then navigates to other pages with tabs (I have an app like that), putting tabs in views won't work.

Anyhow, long story short, you can accomplish what you're looking to do and work around these limitations like so:

```javascript
// TabsActions.js

export const tabHome = () => navigateTo('/tabs/', true);
export const tabPage2 = () => navigateTo('/tabs/page2/', true);
export const tabPage3 = () => navigateTo('/tabs/page3/', true);
```

```javascript
// HomeTabsActions.js

export const goToCatalog = () => navigateTo('/tabs/home-catalog/', true);
export const goBackFromCatalog = () => navigateTo('/tabs/', true);
```

I didn't include the actions for the other 2 tabs, but you get the idea. So, when you select catalog from the home tab, it will put in the correct React component, and will replace the current history item. When you want to go back, you won't have history like I explained previously, so you will have to have your back action hard-coded to navigate to where it is supposed to go. If you do this for all 3 tabs, it should work.

The main problem you might have with this approach is that you'll lose your place in each tab when switching to another tab and then switching back. If that's a problem for you, then you could work around the limitation by storing the current URL for each tab in another area of state and then having logic in your actions to navigate to the correct URL for each tab when it is selected.

It would be nice to have improved tab navigation in both Framework7 and Framework7 Redux so these hacks aren't necessary, but that would be quite a big project. For apps that don't require navigating between pages that have different sets of tabs and can deal with having each tab be in a separate view, Framework7 Redux could probably accommodate that by supporting multiple views, which in itself would require a fair amount of work. I have never had a reason to need that for my own projects, since putting each tab in a separate view has never been an option for me, so I never got around to implementing that.

**Comment by ctsrc** [comment]
> It would be nice to have improved tab navigation in both Framework7 and Framework7 Redux so these hacks aren't necessary, but that would be quite a big project.

I agree. I suggest that you create an issue for it in the issues of this repo with the details about what is missing for Framework7 Redux to support this (similar to what you outlined in the comment above but without the added "noise" of my other comments) and tag it with the "help wanted" label. That way someone that has time to do the work could find the issue and decide to implement it.

Anyway, thanks for the workaround :)
